name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Jenkins Job Trigger
        uses: estherk0/jenkins-trigger@1.0
        with:
          url: "http://jk.toctoc.com"
          username: "mhurtado"
          api_token: "11166a79f3b38c81b5aae603b808c2c974"
          job_name: "e2e_ui_test"
          parameter: "SuperSecret"
          wait: true
          timeout: 600






        
      
      
        

