name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: Mariela2020/demo_e2e_ui_test
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm test
        

