name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build job jenkins
    runs-on: ubuntu-latest
    steps:
    - name: jenkins-action-parametrized
      uses: enflo/jenkins-action@0.2.0
      with:
        url: http://localhost:8080/
        user: mhurtado
        token: 113e8fe7672b0823013d81702a26bc41a8
        job: e2e_test
        parameters: test

      
          



          






        
      
      
        

