name: Prueba QA
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
    types: [closed]
jobs:
  trigger:
    name: Trigger Jenkins Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      - name: Trigger Build-Portal
        uses: appleboy/jenkins-action@v0.0.2 
        with:
          url: "http://localhost:8080/"
          user: "mhurtado"
          token: "113e8fe7672b0823013d81702a26bc41a8" 
          job: "e2e_ui_test"

      
          



          






        
      
      
        

