name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@0.0.1
      with:
        url: "http://localhost:8080/"
        user: "mhurtado"
        token: "111d12bdfd6c06e3bb9f075780ecd01d35"
        job: "e2e_test"
      
          



          






        
      
      
        

