name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      
        

