name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Trigger Jenkins Job
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: "${{ secrets.JENKINS_SERVER }}"
          jenkins-job: "e2e_ui_test"
          jenkins-username: ${{ secrets.JENKINS_USERNAME }}
          jenkins-pat: ${{ secrets.JENKINS_PAT }}
          poll-time: (60)
          timeout-value: (120)





        
      
      
        

