name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Trigger a Jenkins Job
        uses: sbitio/trigger-jenkins-job@v1.3
        with:
          JENKINS_USER: "mhurtado"
          JENKINS_TOKEN: "117673c0629e6073950ee567fe9c424bcb"
          JENKINS_HOST: "http://jk.toctoc.com/job/e2e_ui_test/build"





        
      
      
        

