name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  trigger:
    name: TriggerJenkinsBuild
    runs-on: ubuntu-latest
    steps:
      - name: TriggerJenkinsBuild
        uses: stigmelling/jenkins-action@v1.1 
        with:
          jenkinsUrl: "http://127.0.0.1:8080/"
          username: "mhurtado" 
          token: "111d12bdfd6c06e3bb9f075780ecd01d35"
          job: "e2e_test"
          params: "SuperSecret"
          



          






        
      
      
        

