name: Cypress_Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://jk.toctoc.com/"
          user: "mhurtado"
          token: "11166a79f3b38c81b5aae603b808c2c974"
          job: "e2e_ui_test"


      
          



          






        
      
      
        

