name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  trigger:
    name: Triggering Jenkins Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      - name: Trigger Build-Portal
        uses: appleboy/jenkins-action@v0.0.2 
        with:
          url: "http://jk.toctoc.com/"
          user: "mhurtado" 
          token: "11166a79f3b38c81b5aae603b808c2c974"
          job: "e2e_ui_test"               

      
          



          






        
      
      
        

