name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Run Jenkins Job and get build result
        uses: halilsafakkilic/jenkins-action@v1.0.0
        with:
          jenkins-url: "http://localhost:8080"
          jenkins_user: "mhurtado" 
          jenkins-token: "111d12bdfd6c06e3bb9f075780ecd01d35"
          job_name: "e2e_test"
          job_params: "SuperSecret" 
          job_timeout: 60
          async: false
          debug: true



          






        
      
      
        

