name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Build Jenkins job
        uses: GoldenspearLLC/build-jenkins-job@1.0.0
        with:
          jenkins-url: "http://localhost:8080"
          jenkins-token: "111d12bdfd6c06e3bb9f075780ecd01d35"
          user: "mhurtado"
          job-path: "e2e_test"
          job-params: "SuperSecret" 
          






        
      
      
        

