name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Trigger Jenkins Job
        uses: estherk0/jenkins-trigger@1.0
        with:
          url: "http://jk.toctoc.com/job/e2e_ui_test/"
          username: "mhurtado"
          api_token: "117673c0629e6073950ee567fe9c424bcb"
          job_name: "e2e_ui_test"
          wait: true
          timeout: 600





        
      
      
        

