name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Trigger Jenkins Job
        uses: estherk0/jenkins-trigger@1.0
        with:
          url: "${{ secrets.JENKINS_SERVER }}"
          username: ${{ secrets.TOKEN_JENKINS_USERNAME }}
          job_name: "e2e_ui_test"
          timeout: 600





        
      
      
        

