name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start   
      - name: Trigger a Jenkins Job
        uses: sbitio/trigger-jenkins-job@v1.3
        with:
          JENKINS_USER: "mhurtado"
          JENKINS_TOKEN: "111d12bdfd6c06e3bb9f075780ecd01d35"
          JENKINS_HOST: "http://localhost:8080"
          JENKINS_JOB: "e2e_test"
          JENKINS_PARAMS: "SuperSecret"






        
      
      
        

