name: Test QA
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  trigger:
    name: Trigger Jenkins Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
      - name: Trigger Build-Portal
        uses: appleboy/jenkins-action@v0.0.2 
        with:
          url: ${{ secrets.JENKINS_SERVER }}
          user: ${{ secrets.JENKINS_USERNAME }} 
          token: ${{ secrets.TOKEN }}
          job: "e2e_ui_test"

      
          



          






        
      
      
        

