name: Cypress Test
on:
  push:
    branches: [master]
  pull_request:
    branches: 
    - '**'
    - '!desarrollo'
jobs:
  trigger:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Build Jenkins job
        uses: GoldenspearLLC/build-jenkins-job@1.0.0 
        with:
          jenkins-url: "http://127.0.0.1:8080/"
          user: "mhurtado" 
          jenkins-token: "111d12bdfd6c06e3bb9f075780ecd01d35"
          job-path: "e2e_test"
      
          



          






        
      
      
        

